# Generated by Django 6.0 on 2025-12-09 08:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя автора')),
                ('biography', models.TextField(blank=True, verbose_name='Биография')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название книги')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)], verbose_name='Год выпуска')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('category', models.CharField(choices=[('fiction', 'Художественная литература'), ('textbook', 'Учебник')], max_length=20, verbose_name='Категория')),
                ('publisher', models.CharField(max_length=100, verbose_name='Издательство')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка')),
                ('file', models.FileField(blank=True, null=True, upload_to='books/', verbose_name='Файл книги')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['title', 'year'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('category', 'textbook')), fields=('title', 'author', 'year', 'publisher'), name='unique_textbook_edition'), models.UniqueConstraint(condition=models.Q(('category', 'fiction')), fields=('title', 'author', 'publisher'), name='unique_fiction_edition')],
            },
        ),
    ]
